### ISSUE TITLE
Invalid syntax on Line 151

### ISSUE THREAD

**Issue by galli-a** [Seanld/Latte#4]
After a fresh install I get this error. It is due to two consecutive `+` signs before the variable `nickname`, even though this does not show up in the github page.
Not sure how this happens, but tried multiple times just to make sure I wasn’t doing anything strange. 

![img_0028](https://user-images.githubusercontent.com/2351425/28751700-d008e1a6-750e-11e7-928f-8e470ee70418.JPG)

**Comment by cclauss** [comment]
The problem here is `++` when there should be one.  This looks like it was fixed by https://github.com/Seanld/Latte/commit/bd9c64850c7a0c2808051962a0271fa33682a8ac

**Comment by galli-a** [comment]
Yes, that's fixed on branch `master`. But the installer retrieves the file on branch `dev`, and there the issue is still present

**Comment by Seanld** [comment]
@galli-a it's definitely weird. But I got it fixed by just clearing Pythonista from my apps by doing double home button click and swiping Pythonista up, then re-opening it up and installing Latte. It seems that Pythonista or the `requests` module _may_ be storing caches of the websites it's already downloaded from? Anyways, just restart Pythonista and reinstall Latte and it should work.

**Comment by galli-a** [comment]
Actually it was not that. The installation instructions point to `installer.py` in the `master` branch, which in turn fetches `Latte.py` from the `dev` branch. Yesterday's commit fixed the issue in the `dev` branch as well, but there is still the issue with the `os` imports. That has been fixed in the `master` branch. My proposal is that the `installer.py` for each branch points to the main file for the corresponding branch, not always `dev`. In any case, this particular issue is fixed, and we can close it if you agree.

**Comment by Seanld** [comment]
@galli-a hmm. That's weird. Yeah, I'll close it.
